# apiVersion: v1
# kind: Service
# metadata:
#   name: authentication-server-example-service
# spec:
#   selector:
#     app: authentication-server-example   # Debe coincidir con la etiqueta de tus pods/deployment
#   ports:
#     - protocol: TCP
#       port: 8000        # Puerto expuesto dentro del cluster
#       targetPort: 8000  # Puerto en el contenedor Flask
#       nodePort: 30080   # nodePort es el puerto en el nodo para acceder desde fuera del cluster
#   type: NodePort        # Cambia a LoadBalancer si usas un cloud provider


apiVersion: v1
kind: Service
metadata:
  name: authentication-server-example-service
  annotations:
    ingress_path: "/api/v1/authentication" # Anotaci√≥n personalizada para indicar el path de la API
spec:
  selector:
    app: authentication-server-example
  ports:
    - protocol: TCP
      port: 8000 # Puerto expuesto dentro del cluster
      targetPort: 8000 # Puerto en el contenedor Flask
  type: ClusterIP


