# ingress.yaml
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: authentication-server-example-ingress
# spec:
#   rules:
#   - host: vg-hc-store.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: authentication-server-example-service
#             port:
#               number: 80